### ISSUE TITLE
Doesnt work with terraform 1.12 - fails to validate

### ISSUE THREAD

**Issue by seanmcg-maru** [zilliztech/terraform-provider-zillizcloud#101]
Trying to use your provider with terraform 1.12 fails due to; 

```
│ Error while loading schemas for plugin components: Failed to obtain
│ provider schema: Could not load the schema for provider
│ registry.terraform.io/zilliztech/zillizcloud: failed to retrieve schema
│ from provider "registry.terraform.io/zilliztech/zillizcloud": Provider
│ GetResourceIdentitySchemas Not Implemented: A GetResourceIdentitySchemas
│ call was received by the provider, however the provider does not implement
│ the call. Either upgrade the provider to a version that implements resource
│ identity support or this is a bug in Terraform that should be reported to
│ the Terraform maintainers...
```

Any plans to fix?

**Comment by seanmcg-maru** [comment]
Is there any plans to fix?

**Comment by kiyor** [comment]
Can you offer your terraform basic code here, I can take look. I was just tested terraform 1.12 with following sample provider code, that works.

```
$ terraform init
Initializing the backend...
Initializing provider plugins...
- Finding latest version of zilliztech/zillizcloud...
- Installing zilliztech/zillizcloud v0.6.1...
- Installed zilliztech/zillizcloud v0.6.1 (signed by a HashiCorp partner, key ID D8E83EF2106F68C7)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://developer.hashicorp.com/terraform/cli/plugins/signing
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ ls
provider.tf
$ cat provider.tf
terraform {
  required_providers {
    zillizcloud = {
      source = "zilliztech/zillizcloud"
    }
  }
}

provider "zillizcloud" {
#  api_key = (env $ZILLIZCLOUD_API_KEY)
}
```

**Comment by kiyor** [comment]
Please upgrade the provider to v0.6.4. validate error been fixed
